### ISSUE TITLE
MinGW support

### ISSUE THREAD

**Issue by rashil2000** [akinomyoga/cxxmatrix#10]
Really want to get a working cmatrix binary - couldn't find anything anywhere. 

[cmatrix](https://github.com/abishekvashok/cmatrix) has some [issues](https://github.com/abishekvashok/cmatrix/issues/40) in compiling. 

I tried cxxmatrix, but some headers are not available in Msys/MinGW64, namely - 
- <sys/ioctl.h>
- <termios.h>
- <poll.h>

Any way to get it working?

**Comment by akinomyoga** [comment]
Thank you for the suggestion.

> cmatrix has some issues in compiling.

The `cmatrix` issue you mentioned is about Cygwin, which is different from MinGW/MSYS. Also, MSYS and MSYS2 are different. Which platform are you actually talking about? `cxxmatrix` actually compiles under Cygwin where these headers are available.

Do you really want to use MinGW to obtain a standalone binary of `cxxmatrix` which don't require the Cygwin runtime? Then, there are also additional questions: Which types of terminal/console do you assume for the target of the obtained binary?---Command prompt, Console PTY, MinTTY, Windows PowerShell API, or Windows GUI 32 API (actually I'm not so good at this field so maybe something is missing or duplicate)? Depending on the types of the terminal/console, the code would be completely different, but actually, I'm not really good at all of these different targets. One thing that I'd like to point out is that Windows and Unix are completely different platforms, so there is no real *Unix terminal* in plain Windows, but instead some *Unix terminals* are available only in specific softwares like Cygwin, MinTTY, etc. 

I need some help from those who are familiar with APIs of these completely different types of targets.

**Comment by rashil2000** [comment]
MSYS is no longer under development (since the last 10 years or so). I was referring to MSYS2. 

MSYS2 is a stripped version of Cygwin (that's why it has some missing headers), and compiles stuff using MinGW toolset and headers. It doesn't require and depend on the Cygwin runtime. Ideally, something compiled with MinGW should run independently of any third-party runtimes. 

mintty is a unix-y terminal that's available on both Cygwin and MSYS2. mintty's data is also present in the `terminfo` database. 

Regarding which terminal to target, I think the answer for that would be mintty. But what comes to my mind is this - when I SSH into a linux system, my (host) terminal is irrelevant - cmatrix will run on any of the terminals you mentioned above. So I'm not entirely sure if targeting a particular terminal is something that is done.

**Comment by akinomyoga** [comment]
> So I'm not entirely sure if targeting a particular terminal is something that is done.

OK, the target is MinTTY/MSYS2.

Actually, I have never checked how MinTTY has supported MSYS2 where these headers related to the PTY are missing. Maybe there is actually support for the PTY in MSYS2 but just the headers are missing, or maybe MinTTY implements a bridge or uses a third-party bridge.

Let me check... Ah, OK. I checked my installation of MinGW/MSYS2. Actually, MSYS2 applications and MinGW applications are different. MSYS2 seems to be a runtime just like its fork source Cygwin, and any MSYS2 applications including MinTTY on MSYS2, Bash on MSYS2, etc. relies on the runtime `msys-2.0.dll` and related resources. MinGW applications can be compiled using the MSYS2 toolchain, but the resulting binary doesn't depend on the MSYS2 runtime. So MSYS2 applications and MinGW applications are different types of programs.

Then, the question is: Do you want to compile a binary for MSYS2 (which requires MSYS2 runtime)? Or do you want to compile an independent binary? If you are going to use the resulting binary with MinTTY/MSYS2, we can assume there is always the MSYS2 runtime, so maybe what you want is not the genuine MinGW binary, but the binary that requires the MSYS2 runtime.

**Comment by rashil2000** [comment]
> > So I'm not entirely sure if targeting a particular terminal is something that is done.
> 
> OK, the target is MinTTY/MSYS2.

Sorry for asking again, but I'm still having slightly hard time grasping how finally it's related to the terminal. Even cmatrix on WSL sessions works mighty fine on Windows Console (old terminal), Windows Terminal (new one), or any terminal for that matter.

> ... or maybe MinTTY implements a bridge or uses a third-party bridge.

It has its own implementation of PTY. But sometime around 2016, Microsoft added PTY support to Windows itself, so now mintty can use that too.

> MinGW applications can be compiled using the MSYS2 toolchain, but the resulting binary doesn't depend on the MSYS2 runtime. So MSYS2 applications and MinGW applications are different types of programs.

That's correct!

> Then, the question is: Do you want to compile a binary for MSYS2 (which requires MSYS2 runtime)? Or do you want to compile an independent binary? If you are going to use the resulting binary with MinTTY/MSYS2, we can assume there is always the MSYS2 runtime, so maybe what you want is not the genuine MinGW binary, but the binary that requires the MSYS2 runtime.

I think the binary which doesn't require `msys-2.0.dll` would be much more portable, because not everyone will have MSYS2 installed on their PC (even if installed, it's not guaranteed that the `dll` would pe present in **PATH**). Also, not depending on the MSYS2 runtime would make it possible to use other terminals too.

**Comment by akinomyoga** [comment]
> Sorry for asking again, but I'm still having slightly hard time grasping how finally it's related to the terminal.

Sorry, when I said *terminal/console* in the above replies, I didn't mean a specific terminal emulator such as MinTTY or Windows Terminal, but I tried to mean which type of *terminal/console* API, i.e., which implementation of PTY (pseudo terminal) or some other Windows API you assume. I raised terminal names to probe which type of PTY is suitable for you. For example, the command prompt is tightly bound to the old Windows Console API. MinTTY/MSYS2 is tightly bound to some other type of API (which was MSYS2 PTY). I don't know the details about PowerShell, but it should also have native support to one specific type of PTY.

> Even cmatrix on WSL sessions works mighty fine on Windows Console (old terminal), Windows Terminal (new one), or any terminal for that matter.

That's because they use bridges between different types of PTY. `cmatrix` on WSL are implemented on PTY in WSL, but using some bridges it becomes possible to use it from other types of pty/terminal/consoles. But actually, bridges are not perfectly transparent, i.e., some problems can still happen on some edge/corner cases. For example, last year, Cygwin has paid many efforts to integrate the ConPTY into its PTY and solved many issues, but I believe it's still not perfectly transparent.

That said, when one writes a terminal application, one needs to choose one type of PTY that the terminal application bases on. So I asked which type of PTY implementation you assume.
- If you aim to use it as a MSYS2 application, it is natural to implement it on top of MSYS2 PTY.
- If you want a binary that works without MSYS2, maybe we can investigate how we can implement it on ConPTY. In that case, what I don't know is how to implement IOCTL requests for ConPTY. But I'm not even sure if there are any documented APIs for ConPTY for the terminal applications (I can find APIs for terminal emulators but not for terminal applications). Maybe ConPTY isn't actually a PTY but a bridge between the unix-style PTY and Windows Console...

> > ... or maybe MinTTY implements a bridge or uses a third-party bridge.
>
> It has its own implementation of PTY.

I couldn't find information on PTY implemented by MinTTY. Could you give me some pointer? Is that really PTY implemented in MinTTY? Maybe it is an own implementation of the bridge for an existing PTY?

> But sometime around 2016, Microsoft added PTY support to Windows itself,

Do you mean ConPTY (which I meant by "Windows Console PTY" in my first reply---OK, I thought "Windows ConPTY" stands for "Windows Console PTY", but it actually seems to be "Windows Pseudo Console")? I now searched but ConPTY seems to have appeared around 2018. Is there another implementation of PTY by Microsoft?

> I think the binary which doesn't require msys-2.0.dll would be much more portable, because not everyone will have MSYS2 installed on their PC (even if installed, it's not guaranteed that the dll would pe present in PATH). Also, not depending on the MSYS2 runtime would make it possible to use other terminals too.

Then, maybe what we need is to find a replacement of IOCTL, the way to access the console information in Windows ConPTY. For example, how to get the current terminal size in Windows ConPTY (maybe it's the same as just the legacy Windows console)?

We need help from those who have experience in writing Windows-native console applications through ConPTY.

**Comment by rashil2000** [comment]
> I couldn't find information on PTY implemented by MinTTY. Could you give me some pointer? Is that really PTY implemented in MinTTY? Maybe it is an own implementation of the bridge for an existing PTY?

Correction on my side: It seems MSYS2 and Cygwin both use [winpty](https://github.com/rprichard/winpty). If I'm wrong, probably the developer of @mintty himself can provide more accurate details (if it's not too much trouble 😅)

> Do you mean ConPTY?

Yes.

>Then, maybe what we need is to find a replacement of IOCTL for ConPTY, the way to access the console information in Windows ConPTY. For example, how to get the current terminal size in Windows ConPTY (maybe it's the same as just the legacy Windows console)?

You can refer to the docs here [link 1](https://docs.microsoft.com/en-us/windows/console/classic-vs-vt), [link 2](https://docs.microsoft.com/en-us/windows/console/window-and-screen-buffer-size). 

One more thing I'd like to mention - I don't know if it's helpful in any way, but still. Running tmux natively on Windows (by native I mean Windows binaries produced from environments like Cygwin or MSYS2) is possible only on mintty - it just plain refuses to recognize any other terminals. Though it seems like a [bug](http://cygwin.1069669.n5.nabble.com/quot-tmux-open-terminal-failed-not-a-terminal-quot-in-terminal-emulators-other-than-mintty-td150569.html) with Cygwin itself. This might, in the worst case, mean that running cxxmatrix might be possible only in mintty.

**Comment by mintty** [comment]
winpty isn't active anymore. Cygwin has never used it. Cygwin 3.1 introduced built-in ConPTY support, cygwin 3.2 will change that to automatic ConPTY support for non-cygwin applications only. MSYS2 currently disables ConPTY support by default.
The current download of cxxmatrix compiles here on both cygwin and MSYS2 and runs in any terminal.

**Comment by mintty** [comment]
(... as compared to https://github.com/abishekvashok/cmatrix which does not build for me)

**Comment by rashil2000** [comment]
May I ask how you resolved the missing headers? (Or what package I can use to install them, using pacman?)

**Comment by mintty** [comment]
OK, unspecified build dependencies are a frequent and annoying problem.
On http://cygwin.com/packages/ you can look up packages to resolve certain files.

**Comment by rashil2000** [comment]
Sorry, I was asking about MSYS2/MinGW, I don't currently have Cygwin installed.

**Comment by mintty** [comment]
As a first guess, I would assume packages have the same name in MSYS2, so just try to install them with pacman.

**Comment by rashil2000** [comment]
Okay, I installed the `msys2-runtime-devel` package, which had all the three headers I mentioned at the top of this thread. The header files are now in `/usr/include/` folder, but running `make` still gives an error about not being able to find the file. 

Do I need to somehow change the system's includepath?

**Comment by rashil2000** [comment]
As a temporary measure, I ran `export CPLUS_INCLUDE_PATH=/usr/include`. This resolves the header issue, but compilation still fails after giving an entire wall of errors :(

Here's the log https://www.pastiebin.com/605e448fe0efc

**Comment by mintty** [comment]
I only stepped in because I was addressed about winpty. I did not take notice this issue is about MinGW explicitly.
Note there are two toolchains on MSYS2 (on cygwin as well), MSYS and MinGW. I was trying the MSYS toolchain which works.

**Comment by rashil2000** [comment]
Oh, okay. Thanks for the info, I'll try that!

**Comment by rashil2000** [comment]
**Update**:

Sorry for nagging this really old issue of mine, but I made a [couple](https://github.com/abishekvashok/cmatrix/pull/131) of [fixes](https://github.com/abishekvashok/cmatrix/pull/132) to cmatrix upstream, and now it compiles successfully under both MinGW and MSys2 toolchains.

Since cxxmatrix already compiles under MSys2 toolchain, this issue was about obtaining a standalone binary for Windows (which meant MinGW needs to be used). 

> Then, maybe what we need is to find a replacement of IOCTL for ConPTY, the way to access the console information in Windows ConPTY. For example, how to get the current terminal size in Windows ConPTY (maybe it's the same as just the legacy Windows console)?

I think a good place to start looking for this info is the 800-line cmatrix.c file itself. It has many `#ifdef _WIN32` directives, which define the Windows counterparts. For example, this line https://github.com/abishekvashok/cmatrix/blob/0365a637fd6784db4238449075b1b25f68aea274/cmatrix.c#L265
tells us the terminal size.

**Comment by akinomyoga** [comment]
`cmatrix` is licensed by GPL, which is viral, while `cxxmatrix` is by MIT license. You want to learn that posting GPL codes to the community of a non-GPL product can be a serious attack on that product. We cannot reference the implementation of `cmatrix` for even a single line (as there is no clear worldwide definition of copyrightable codes). Even some people would say something like, if you learned that some API can be used for some specific purpose from the GPL'ed code, you cannot use the API in non-GPL codes for that specific purpose *forever*.

Actually, I have already opened the first link, which was a mistake, and found that `GetConsoleScreenBufferInfo`, which I know is the API of the legacy Windows console, is used there. Huh, I will ignore the copyright of this line because I think this code is trivial (though the original copyright holder of this line might insist opposite). I'm not sure if `cmatrix` targets the legacy Windows console or targets the ConPTY. But if it targets the latter, this means that this API can be used for both the legacy Windows console and the ConPTY, which is likely because [the ConPTY article](https://devblogs.microsoft.com/commandline/windows-command-line-introducing-the-windows-pseudo-console-conpty/#command-line-application-developers) is written as if the only difference between the legacy console and ConPTY from the application side is that the latter interprets the VT sequences. I won't open the other link.

**Comment by rashil2000** [comment]
I have to admit it was a grievous oversight on my part. I'd like to sincerely apologize. I have edited my comment, sorry for the mistake. I'll try to post references to Microsoft's own documentation instead.

Targeting the new ConPTY API would be better in the long run, I feel, because it's currently the recommended way and it also gives abilities like 24bit colors (like the article mentions).

**Comment by akinomyoga** [comment]
I have added support for ConPTY. Could you test the latest version by following the instruction in README?

**Comment by rashil2000** [comment]
I have tested it. It builds and runs. It is extremely slow, as you noted in the Readme.

Thank you for your efforts!

Should I close this (since the original issue of building with MinGW is resolved)?

**Comment by akinomyoga** [comment]
OK! Thank you for testing! You can now close the issue.
